Details popup window
MarcoOquendoC/Portfolio pull request #12
Opened 2022-07-22 21:12 UTC by MarcoOquendoC

# [Portfolio: details popup window](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md)

## Hi good reviewer,

![Have a good day bear](https://user-images.githubusercontent.com/104022866/178123015-020aa258-2a43-4303-a0eb-36f15d27c526.gif)

### These are the [changes](https://github.com/MarcoOquendoC/Portfolio/tree/details-popup-window) proposed to the [Portfolio](https://github.com/MarcoOquendoC/Portfolio) project:

[README.md]()
[index.html](https://github.com/MarcoOquendoC/Portfolio/blob/mobile-menu/index.html)
[styles.css](https://github.com/MarcoOquendoC/Portfolio/blob/mobile-menu/styles.css)
[script.js](https://github.com/MarcoOquendoC/Portfolio/blob/mobile-menu/script.js)

#### Project requirements
- Implement the following interactions:
  - When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
  - When the user clicks (or taps) the close (X) button, the popup disappears.

- You should implement popups for both mobile and desktop screen sizes:

- In order to associate each project with the popup window details. Use a JavaScript array to store all of the information for all projects.
  - For each project. Store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
  - Update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
  - Implement the popup window.

2022-07-22 22:43 UTC, MeqdamAlqudah requested changes
Hi @MarcoOquendoC , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 22:43 UTC, MeqdamAlqudah commented on index.html
>        </h2>
- [ ] Please fix linter errors 
![image](https://user-images.githubusercontent.com/74744787/180569947-1594c02c-9028-4978-bf30-9c87d02eca3a.png)

2022-07-22 22:43 UTC, MeqdamAlqudah commented on index.html
> -          <div class="work-card-content">
- [ ] Please make sure that the popup is responsive 
![image](https://user-images.githubusercontent.com/74744787/180571239-9d6e2cb4-4755-4499-a603-384793d7423d.png)

2022-07-22 22:43 UTC, MeqdamAlqudah commented on index.html
> -            <ul class="tags">
- [ ] Please make  sure that your design matches Figma design 

| Your design | Figma design |
| ---------------- | ------------------ |
| ![image](https://user-images.githubusercontent.com/74744787/180577422-3bc9cacd-898d-451a-a3da-0077b89693c9.png) | ![image](https://user-images.githubusercontent.com/74744787/180577466-1dc4bb99-5408-4e75-95a9-98058946a421.png) |

2022-07-23 04:50 UTC, MarcoOquendoC commented
# Hi @MeqdamAlqudah,

## Thank you for your review.

### The changes on the repository are listed below:
- No linter errors.
- Improve responsiveness.
- Change styles to match the figma design.

2022-07-23 20:02 UTC, MeqdamAlqudah approved these changes
@MarcoOquendoC , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-09 06:36 UTC, merged