Accessibility Features
MarcoOquendoC/Portfolio pull request #8
Opened 2022-07-12 19:59 UTC by MarcoOquendoC

Change title

change alt name for hamburger icon

headings checked

increase font weight for primary buttons

increase font size on tags

Resize no changes required

Interactions no changes required

Moving content no changes required

Multimedia no changes required

Structure no changes required

2022-07-12 20:01 UTC, MarcoOquendoC commented on index.html
> +          <li><a href="#"><img src="images/angellist.png" alt="angellist"></a></li>
Change

2022-07-12 21:53 UTC, codecaiine requested changes
Hi @MarcoOquendoC , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
- Great UI :heavy_check_mark:
- Clean code :heavy_check_mark:  

## Required Changes ♻️

- [ ] Please modify the button's contrast. You can check it with [Aditus](https://www.aditus.io/button-contrast-checker/) 
- [ ] Please check your single project technologies list Contrast Errors because it is very low
- [ ] Your 3 contact form labels are missing, please add them because labels are there to connect an explanatory text with a form element.

![Screenshot from 2022-07-12 21-53-08](https://user-images.githubusercontent.com/6615394/178602049-bb70d8f6-902e-4223-9fda-e43d5a031b34.png)

![Screenshot from 2022-07-12 21-49-09](https://user-images.githubusercontent.com/6615394/178601726-f1bb7f4b-45b4-4a9c-b7d3-d215fb871115.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- I would like to recommend you include this extension in your browser's tab. You can follow [this link](https://stackoverflow.com/questions/4888377/how-to-add-a-browser-tab-icon-favicon-for-a-website).


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-13 10:37 UTC, algerina approved these changes
Hi @MarcoOquendoC , 
Good job so far!

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 

 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-13 11:43 UTC, merged

2022-07-13 14:41 UTC, MarcoOquendoC commented
## Thank you @codecaiine and @algerina.
Keep making microverse a great place to learn coding.

![giphy](https://user-images.githubusercontent.com/104022866/178371851-5c34cc13-5504-44b2-830a-ef2004a1750f.gif)